#!/usr/bin/env node
// Bundles test262's `intl402/NumberFormat` tests, with the harness files they
// include, into a module the example app runs on a device
// (example/__tests__/test262-number-format.harness.tsx): every test once
// against Hermes' Intl.NumberFormat and once against the library's
// NumberFormat.
//
// test262 is fetched at a pinned commit into scripts/test262/.cache (a sparse
// checkout of the two folders needed); the bundle is generated, not
// committed.
//
//   node scripts/test262/number-format.mjs
import { execFileSync } from 'node:child_process'
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const COMMIT = '7ab7fafa0003f73fc85c1b95d88094d33f7eb8bd' // 2026-09-23
const here = path.dirname(fileURLToPath(import.meta.url))
const root = path.resolve(here, '../..')
const checkout = path.join(here, '.cache/test262')
const out = path.join(root, 'example/__tests__/test262/number-format.generated.js')

const git = (...args) => execFileSync('git', args, { cwd: checkout, stdio: ['ignore', 'pipe', 'inherit'] }).toString().trim()

if (!fs.existsSync(path.join(checkout, '.git'))) {
  fs.mkdirSync(checkout, { recursive: true })
  execFileSync('git', ['clone', '--filter=blob:none', '--no-checkout', 'https://github.com/tc39/test262', checkout], { stdio: 'inherit' })
}
if (git('rev-parse', 'HEAD').startsWith(COMMIT) === false || !fs.existsSync(path.join(checkout, 'test/intl402/NumberFormat'))) {
  git('sparse-checkout', 'set', '--no-cone', '/test/intl402/NumberFormat/', '/harness/')
  try {
    git('checkout', '-q', COMMIT)
  } catch {
    git('fetch', '-q', 'origin', COMMIT)
    git('checkout', '-q', COMMIT)
  }
}

/** The YAML front matter's includes, flags, features and negative expectation. */
function metadata(source) {
  const yaml = /\/\*---([\s\S]*?)---\*\//.exec(source)?.[1] ?? ''
  const list = (key) => {
    const inline = new RegExp(`^${key}:\\s*\\[([^\\]]*)\\]`, 'm').exec(yaml)
    if (inline) return inline[1].split(',').map((s) => s.trim()).filter(Boolean)
    const block = new RegExp(`^${key}:\\s*\\n((?:\\s+-\\s*.+\\n?)+)`, 'm').exec(yaml)
    return block ? block[1].split('\n').map((l) => l.replace(/^\s*-\s*/, '').trim()).filter(Boolean) : []
  }
  const negative = /^negative:\s*\n\s+phase:\s*(\w+)\s*\n\s+type:\s*(\w+)/m.exec(yaml)
  return {
    includes: list('includes'),
    flags: list('flags'),
    features: list('features'),
    negative: negative ? { phase: negative[1], type: negative[2] } : null,
  }
}

const testsDir = path.join(checkout, 'test/intl402/NumberFormat')
const files = []
const walk = (dir) => {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name)
    if (entry.isDirectory()) walk(full)
    else if (entry.name.endsWith('.js') && !entry.name.includes('_FIXTURE')) files.push(full)
  }
}
walk(testsDir)
files.sort()

const harness = {}
const tests = files.map((file) => {
  const source = fs.readFileSync(file, 'utf8')
  const meta = metadata(source)
  for (const name of ['assert.js', 'sta.js', ...meta.includes]) {
    harness[name] ??= fs.readFileSync(path.join(checkout, 'harness', name), 'utf8')
  }
  return { path: path.relative(path.join(checkout, 'test'), file), ...meta, source }
})

fs.mkdirSync(path.dirname(out), { recursive: true })
fs.writeFileSync(
  out,
  `// Generated by scripts/test262/number-format.mjs from tc39/test262@${COMMIT.slice(0, 12)}. Do not edit.\n` +
    `module.exports = ${JSON.stringify({ commit: COMMIT, harness, tests })}\n`,
)
console.log(`wrote ${path.relative(root, out)}: ${tests.length} tests, ${Object.keys(harness).length} harness files`)
